import type { LegalIssueTaxonomyEntry } from "@/lib/legal/legal-issue-taxonomy-data";

/**
 * Consumer-facing legal issues (UK): goods, services, finance, travel, utilities, and disputes.
 * These slugs power natural-language query understanding and directory practice-area filtering.
 */
export const LEGAL_ISSUE_TAXONOMY_CONSUMER: LegalIssueTaxonomyEntry[] = [
  {
    slug: "consumer_goods",
    canonicalName: "Faulty Goods and Refunds",
    matcherSlug: "commercial",
    aliases: [
      "faulty product",
      "broken product",
      "defective goods",
      "consumer rights act",
      "sale of goods",
      "not fit for purpose",
      "not as described",
    ],
    userPhrases: [
      "faulty goods",
      "broken phone",
      "laptop stopped working",
      "refund refused",
      "shop won't refund",
      "shop wont refund",
      "refund faulty",
      "retailer won't replace",
      "warranty claim refused",
      "goods not as described",
      "item never arrived",
      "wrong item delivered",
      "missing parts",
      "appliance broke down",
    ],
    subIssues: [
      "Refunds and replacements",
      "Consumer Rights Act 2015",
      "Manufacturer warranty",
      "Chargeback disputes",
      "Delivery failures",
    ],
    relatedPracticeAreas: ["Consumer law", "Online shopping", "Small claims"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Did you buy in a shop, online, or from a private seller — and roughly when?",
    ],
    searchBoostTerms: [
      "faulty goods",
      "refund",
      "replacement",
      "Consumer Rights Act",
      "not of satisfactory quality",
      "trader",
      "retailer",
      "manufacturer",
      "warranty",
    ],
  },
  {
    slug: "consumer_services",
    canonicalName: "Poor Services and Traders",
    matcherSlug: "commercial",
    aliases: [
      "poor service",
      "trader dispute",
      "unsatisfactory service",
      "service not provided",
      "cowboy builder",
    ],
    userPhrases: [
      "builder didn't finish the job",
      "tradesman dispute",
      "poor workmanship",
      "service not as promised",
      "contractor took my money",
      "home improvement gone wrong",
      "kitchen fitter problem",
      "bathroom installation dispute",
      "decorator dispute",
      "cleaning company complaint",
      "salon treatment went wrong",
    ],
    subIssues: [
      "Home improvements",
      "Tradespeople",
      "Professional services",
      "Cancellation rights",
      "Deposit disputes",
    ],
    subIssueRules: [
      {
        label: "Cancellation rights",
        anyTerms: [
          "cancel",
          "cancelled",
          "cancellation",
          "don't want to go ahead",
          "not going ahead",
          "changed my mind",
          "owe him",
          "owe her",
          "wants me to pay",
          "wants me to transfer",
          "booking fee",
          "cancellation fee",
        ],
        excludeTerms: ["flight cancel", "package holiday cancel"],
      },
      {
        label: "Deposit disputes",
        anyTerms: ["deposit", "upfront payment", "holding fee"],
        excludeTerms: ["tenancy deposit", "rent deposit"],
      },
      {
        label: "Tradespeople",
        anyTerms: [
          "tradesman",
          "tradesmen",
          "tiler",
          "builder",
          "plumber",
          "electrician",
          "roofer",
          "decorator",
          "handyman",
          "fitter",
        ],
      },
    ],
    relatedPracticeAreas: ["Construction law", "Consumer law", "Small claims"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Was there a written quote or contract, and have you paid a deposit or the full amount?",
    ],
    searchBoostTerms: [
      "poor service",
      "trader",
      "workmanship",
      "builder",
      "contractor",
      "home improvement",
      "Consumer Rights Act services",
    ],
  },
  {
    slug: "consumer_online_shopping",
    canonicalName: "Online Shopping and Distance Selling",
    matcherSlug: "commercial",
    aliases: [
      "online purchase",
      "distance selling",
      "e-commerce dispute",
      "internet shopping",
      "marketplace dispute",
    ],
    userPhrases: [
      "bought online",
      "Amazon won't refund",
      "Amazon order never arrived",
      "order never arrived",
      "eBay seller dispute",
      "online order never arrived",
      "return refused online",
      "cooling off period",
      "14 day return",
      "cancel online order",
      "fake website",
      "dropshipping scam",
      "AliExpress dispute",
      "Vinted dispute",
    ],
    subIssues: [
      "Returns and cooling-off",
      "Non-delivery",
      "Marketplace sellers",
      "Chargebacks",
      "Counterfeit goods",
    ],
    relatedPracticeAreas: ["Faulty goods", "Consumer law", "Scams"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Which website or platform did you buy from, and do you still have order confirmation?",
    ],
    searchBoostTerms: [
      "online shopping",
      "distance contract",
      "cooling off",
      "Consumer Contracts Regulations",
      "marketplace",
      "chargeback",
      "PayPal dispute",
    ],
  },
  {
    slug: "consumer_travel_holidays",
    canonicalName: "Travel and Holiday Disputes",
    matcherSlug: "commercial",
    aliases: [
      "holiday complaint",
      "package holiday",
      "flight cancelled",
      "travel dispute",
      "ATOL claim",
    ],
    userPhrases: [
      "holiday ruined",
      "hotel not as advertised",
      "holiday not as described",
      "nothing like the brochure",
      "package holiday complaint",
      "travel company won't refund",
      "cancelled holiday",
      "flight cancelled refund",
      "lost luggage compensation",
      "cruise complaint",
      "travel agent dispute",
      "ABTA complaint",
      "ATOL protected",
      "holiday illness claim",
    ],
    subIssues: [
      "Package Travel Regulations",
      "Flight cancellations",
      "Accommodation misdescription",
      "Travel insurance",
      "Timeshare (travel)",
    ],
    relatedPracticeAreas: ["Aviation law", "Consumer law", "Personal injury"],
    emergencySignals: ["stranded abroad"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Was this a package holiday, separate flights/hotel, or a cruise — and who did you book with?",
    ],
    searchBoostTerms: [
      "package travel",
      "holiday complaint",
      "ABTA",
      "ATOL",
      "flight refund",
      "travel ombudsman",
      "Package Travel Regulations",
    ],
  },
  {
    slug: "consumer_motor_purchase",
    canonicalName: "Car Purchase and Dealer Disputes",
    matcherSlug: "commercial",
    aliases: [
      "used car dispute",
      "car dealer problem",
      "faulty car",
      "lemon car",
      "car not as described",
    ],
    userPhrases: [
      "bought a faulty car",
      "used car broke down",
      "dealer sold me a dud",
      "car not as described",
      "mileage clocked",
      "car dealer won't help",
      "private car sale dispute",
      "reject the car",
      "car warranty dispute",
      "previously written off",
      "HPI check problem",
    ],
    subIssues: [
      "Rejecting a vehicle",
      "Misdescription",
      "Warranty and guarantees",
      "Private vs dealer sale",
      "Finance linked purchase",
    ],
    relatedPracticeAreas: ["Consumer law", "Car finance", "Motoring"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Did you buy from a dealer or privately, and is the car on finance?",
    ],
    searchBoostTerms: [
      "used car",
      "car dealer",
      "faulty vehicle",
      "Consumer Rights Act car",
      "reject car",
      "Sale of Goods Act vehicle",
    ],
  },
  {
    slug: "consumer_car_finance",
    canonicalName: "Car Finance and PCP Disputes",
    matcherSlug: "commercial",
    aliases: [
      "PCP dispute",
      "car finance complaint",
      "HP agreement",
      "vehicle finance",
      "balloon payment",
    ],
    userPhrases: [
      "PCP mis-sold",
      "car finance complaint",
      "can't afford car payments",
      "voluntary termination car finance",
      "negative equity car",
      "finance company harassment",
      "unfair car loan",
      "hire purchase dispute",
      "PCP balloon payment",
      "car finance ombudsman",
    ],
    subIssues: [
      "PCP and HP",
      "Mis-selling",
      "Affordability",
      "Voluntary termination",
      "FOS complaints",
    ],
    relatedPracticeAreas: ["Consumer credit", "Motor purchase", "Debt"],
    emergencySignals: ["car repossession"],
    legalAidLikely: false,
    clarificationQuestions: [
      "What type of finance is it (PCP, HP, lease), and who is the lender?",
    ],
    searchBoostTerms: [
      "car finance",
      "PCP",
      "hire purchase",
      "FOS",
      "Financial Ombudsman car",
      "Consumer Credit Act",
    ],
  },
  {
    slug: "consumer_credit_loans",
    canonicalName: "Loans, Credit Cards and Unaffordable Lending",
    matcherSlug: "commercial",
    aliases: [
      "payday loan",
      "credit card dispute",
      "unaffordable lending",
      "irresponsible lending",
      "catalogue debt",
    ],
    userPhrases: [
      "payday loan problem",
      "credit card refund",
      "Section 75 claim",
      "section 75 credit card",
      "unaffordable loan",
      "catalogue debt",
      "buy now pay later dispute",
      "Klarna dispute",
      "store card problem",
      "loan mis-sold",
      "interest too high",
      "persistent debt",
    ],
    subIssues: [
      "Section 75",
      "Payday and high-cost credit",
      "Affordability complaints",
      "BNPL schemes",
      "Credit reporting errors",
    ],
    relatedPracticeAreas: ["Debt", "Consumer law", "Financial mis-selling"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about repayments, a refund on a card purchase, or a complaint about how the loan was sold?",
    ],
    searchBoostTerms: [
      "Section 75",
      "Consumer Credit Act",
      "unaffordable lending",
      "FOS",
      "credit card chargeback",
      "payday loan",
    ],
  },
  {
    slug: "consumer_financial_mis_selling",
    canonicalName: "Financial Mis-selling",
    matcherSlug: "commercial",
    aliases: [
      "mis-sold investment",
      "PPI style complaint",
      "pension mis-selling",
      "investment advice complaint",
    ],
    userPhrases: [
      "mis-sold investment",
      "bad financial advice",
      "pension transfer mis-sold",
      "SIPP mis-selling",
      "investment gone wrong",
      "adviser complaint",
      "FCA complaint",
      "Financial Ombudsman",
      "pension scam",
      "high risk investment mis-sold",
    ],
    subIssues: [
      "Pensions and SIPPs",
      "Investments",
      "Mortgage endowments",
      "Advised products",
      "FOS escalation",
    ],
    relatedPracticeAreas: ["Consumer credit", "Debt", "Fraud"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "What product was sold (pension, investment, mortgage-related) and when?",
    ],
    searchBoostTerms: [
      "mis-selling",
      "Financial Ombudsman",
      "FCA",
      "pension transfer",
      "SIPP",
      "investment complaint",
    ],
  },
  {
    slug: "consumer_insurance",
    canonicalName: "Insurance Disputes",
    matcherSlug: "commercial",
    aliases: [
      "insurance claim refused",
      "policy dispute",
      "insurance complaint",
      "denied claim",
    ],
    userPhrases: [
      "insurance won't pay out",
      "claim rejected",
      "home insurance dispute",
      "car insurance claim refused",
      "travel insurance refused",
      "pet insurance won't pay",
      "life insurance dispute",
      "insurance ombudsman",
      "policy cancelled unfairly",
      "excess dispute",
    ],
    subIssues: [
      "Claim refusal",
      "Policy wording",
      "Renewal and auto-renewal",
      "Travel and pet",
      "FOS insurance",
    ],
    relatedPracticeAreas: ["Consumer law", "Personal injury", "Travel"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "What type of insurance is involved, and have you complained to the insurer already?",
    ],
    searchBoostTerms: [
      "insurance claim",
      "policy dispute",
      "FOS insurance",
      "claim refused",
      "Insurance Ombudsman",
    ],
  },
  {
    slug: "consumer_energy_utilities",
    canonicalName: "Energy and Utilities",
    matcherSlug: "commercial",
    aliases: [
      "energy bill dispute",
      "gas and electric complaint",
      "utility overcharge",
      "water bill dispute",
    ],
    userPhrases: [
      "energy company overcharging",
      "wrong energy bill",
      "smart meter dispute",
      "switched supplier problem",
      "back billing",
      "prepayment meter issue",
      "water company complaint",
      "Ofgem complaint",
      "energy ombudsman",
      "forced onto prepayment meter",
      "dual fuel dispute",
    ],
    subIssues: [
      "Billing errors",
      "Switching",
      "Smart meters",
      "Back-billing",
      "Complaints and ombudsman",
    ],
    relatedPracticeAreas: ["Consumer law", "Telecoms", "Debt"],
    emergencySignals: ["disconnection threat"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Which supplier is involved — energy, water, or both — and is it about billing or service?",
    ],
    searchBoostTerms: [
      "energy complaint",
      "Ofgem",
      "utility ombudsman",
      "back billing",
      "Energy Ombudsman",
      "water bill",
    ],
  },
  {
    slug: "consumer_telecoms",
    canonicalName: "Broadband, Mobile and Telecoms",
    matcherSlug: "commercial",
    aliases: [
      "mobile contract dispute",
      "broadband complaint",
      "phone contract",
      "telecoms ombudsman",
    ],
    userPhrases: [
      "broadband not working",
      "mobile provider overcharging",
      "cancel phone contract",
      "exit fee dispute",
      "Ofcom complaint",
      "mid contract price rise",
      "sim only dispute",
      "faulty router compensation",
      "number porting problem",
      "EE complaint",
      "Virgin Media dispute",
    ],
    subIssues: [
      "Contract exit fees",
      "Service failures",
      "Mis-selling bundles",
      "Price rises",
      "Complaints procedure",
    ],
    relatedPracticeAreas: ["Consumer law", "Energy and utilities"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this mobile, broadband, or a bundled service — and are you in or out of contract?",
    ],
    searchBoostTerms: [
      "telecoms",
      "broadband",
      "mobile contract",
      "Ofcom",
      "Communications Ombudsman",
      "exit fee",
    ],
  },
  {
    slug: "consumer_subscriptions",
    canonicalName: "Subscriptions and Memberships",
    matcherSlug: "commercial",
    aliases: [
      "gym membership",
      "subscription trap",
      "auto renewal",
      "membership cancellation",
      "unfair contract terms",
    ],
    userPhrases: [
      "can't cancel subscription",
      "gym won't let me leave",
      "gym wont let me leave",
      "gym wont let me cancel",
      "cancel gym membership",
      "free trial charged me",
      "subscription I didn't sign up for",
      "auto renewal unfair",
      "streaming service dispute",
      "magazine subscription",
      "dating site refund",
      "cooling off subscription",
      "recurring payment unauthorised",
    ],
    subIssues: [
      "Gym and clubs",
      "Digital subscriptions",
      "Continuous payment authority",
      "Unfair terms",
      "Cooling-off rights",
    ],
    relatedPracticeAreas: ["Consumer law", "Online shopping", "Debt"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "What subscription is it, and did you sign online, in person, or over the phone?",
    ],
    searchBoostTerms: [
      "subscription",
      "membership cancellation",
      "continuous payment authority",
      "Consumer Rights Act unfair terms",
      "auto renewal",
    ],
  },
  {
    slug: "consumer_timeshare",
    canonicalName: "Timeshare and Holiday Clubs",
    matcherSlug: "commercial",
    aliases: [
      "timeshare exit",
      "holiday club",
      "timeshare scam",
      "points club",
    ],
    userPhrases: [
      "timeshare problem",
      "exit timeshare contract",
      "timeshare maintenance fees",
      "holiday club scam",
      "timeshare resale scam",
      "can't sell timeshare",
      "timeshare mis-sold",
    ],
    subIssues: [
      "Exit and rescission",
      "Maintenance fees",
      "Resale scams",
      "Mis-selling abroad",
      "Enforcement",
    ],
    relatedPracticeAreas: ["Travel", "Scams", "Consumer law"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "When was the timeshare or club purchased, and is a UK company involved?",
    ],
    searchBoostTerms: [
      "timeshare",
      "holiday club",
      "maintenance fee",
      "timeshare exit",
      "cooling off timeshare",
    ],
  },
  {
    slug: "consumer_funeral_prepaid",
    canonicalName: "Funeral and Prepaid Plans",
    matcherSlug: "commercial",
    aliases: [
      "funeral plan",
      "prepaid funeral",
      "funeral plan mis-sold",
    ],
    userPhrases: [
      "funeral plan problem",
      "prepaid funeral won't honour",
      "funeral plan refund",
      "funeral plan company collapsed",
      "mis-sold funeral plan",
      "funeral costs dispute",
    ],
    subIssues: [
      "Plan mis-selling",
      "Provider insolvency",
      "Plan transfer",
      "Funeral director disputes",
    ],
    relatedPracticeAreas: ["Consumer law", "Wills and probate"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this a prepaid plan complaint, a funeral director dispute, or a plan provider that has closed?",
    ],
    searchBoostTerms: [
      "funeral plan",
      "prepaid funeral",
      "Funeral Planning Authority",
      "funeral ombudsman",
    ],
  },
  {
    slug: "consumer_wedding_events",
    canonicalName: "Weddings and Events",
    matcherSlug: "commercial",
    aliases: [
      "wedding supplier dispute",
      "venue cancellation",
      "event cancellation",
      "photographer dispute",
    ],
    userPhrases: [
      "wedding venue cancelled",
      "photographer didn't show up",
      "photographer didnt show up",
      "wedding photographer no show",
      "wedding deposit lost",
      "supplier went bust",
      "event cancelled refund",
      "caterer dispute",
      "wedding planner problem",
      "marquee company dispute",
    ],
    subIssues: [
      "Deposits and cancellations",
      "Supplier failure",
      "Force majeure",
      "Photography and video",
      "Venue contracts",
    ],
    relatedPracticeAreas: ["Consumer services", "Consumer law"],
    emergencySignals: ["wedding this week"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Which supplier or venue is involved, and what does your contract say about cancellation?",
    ],
    searchBoostTerms: [
      "wedding contract",
      "event cancellation",
      "deposit wedding",
      "supplier breach",
    ],
  },
  {
    slug: "consumer_vehicle_repair",
    canonicalName: "Garage and Vehicle Repair Disputes",
    matcherSlug: "commercial",
    aliases: [
      "garage overcharged",
      "car repair dispute",
      "MOT dispute",
      "mechanic problem",
    ],
    userPhrases: [
      "garage ripped me off",
      "car repair bill too high",
      "work not done properly",
      "MOT failure dispute",
      "garage damaged my car",
      "main dealer overcharging",
      "warranty repair refused",
      "parts not fitted",
    ],
    subIssues: [
      "Overcharging",
      "Poor repairs",
      "MOT and safety",
      "Warranty work",
      "Estimate disputes",
    ],
    relatedPracticeAreas: ["Motor purchase", "Consumer services"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about repair quality, cost, or damage caused during work?",
    ],
    searchBoostTerms: [
      "garage dispute",
      "car repair",
      "MOT",
      "Motor Ombudsman",
      "workmanship vehicle",
    ],
  },
  {
    slug: "consumer_rent_to_own",
    canonicalName: "Rent-to-Own and Catalogue Credit",
    matcherSlug: "commercial",
    aliases: [
      "rent to own",
      "catalogue shopping",
      "weekly payment store",
      "BrightHouse",
    ],
    userPhrases: [
      "rent to own sofa",
      "catalogue debt problem",
      "weekly payment shop",
      "pay weekly furniture",
      "unaffordable weekly payments",
      "goods repossessed",
    ],
    subIssues: ["High-cost credit", "Goods repossession", "Affordability", "Termination rights"],
    relatedPracticeAreas: ["Consumer credit", "Debt", "Faulty goods"],
    emergencySignals: ["repossession visit"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Which company provided the credit, and are you still paying weekly instalments?",
    ],
    searchBoostTerms: [
      "rent to own",
      "catalogue credit",
      "high cost credit",
      "Consumer Credit Act",
      "weekly payments",
    ],
  },
  {
    slug: "consumer_scams_recovery",
    canonicalName: "Scams and Consumer Fraud",
    matcherSlug: "commercial",
    aliases: [
      "scammed online",
      "fraud victim",
      "recovery scam",
      "phishing",
      "authorised push payment",
    ],
    userPhrases: [
      "I was scammed",
      "lost money to fraud",
      "bank won't refund scam",
      "authorised push payment fraud",
      "APP fraud",
      "romance scam",
      "investment scam",
      "crypto scam",
      "recovery scam",
      "fake company took my money",
      "phishing email lost money",
    ],
    subIssues: [
      "Bank refund (APP)",
      "Online fraud",
      "Recovery scams",
      "Action Fraud",
      "Chargeback",
    ],
    relatedPracticeAreas: ["Consumer law", "Banking", "Debt"],
    emergencySignals: ["money transferred today"],
    legalAidLikely: false,
    clarificationQuestions: [
      "How did you pay (bank transfer, card, crypto), and have you reported it to your bank and Action Fraud?",
    ],
    searchBoostTerms: [
      "APP fraud",
      "authorised push payment",
      "scam refund",
      "Contingent Reimbursement Model",
      "Action Fraud",
      "phishing",
    ],
  },
  {
    slug: "consumer_landlord_agent_fees",
    canonicalName: "Letting Agent and Tenant Fees",
    matcherSlug: "housing",
    aliases: [
      "letting agent fees",
      "tenant fees",
      "illegal agency fees",
      "holding deposit agent",
    ],
    userPhrases: [
      "letting agent charging illegal fees",
      "tenant fees Act",
      "agency won't return holding deposit",
      "admin fee letting agent",
      "referencing fee dispute",
      "check out fee unfair",
    ],
    subIssues: [
      "Banned fees",
      "Holding deposits",
      "Check-out charges",
      "Redress schemes",
    ],
    relatedPracticeAreas: ["Housing", "Consumer law"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Which fees were charged, and is the agent registered with a redress scheme?",
    ],
    searchBoostTerms: [
      "Tenant Fees Act",
      "letting agent",
      "holding deposit",
      "agency fees",
      "property ombudsman",
    ],
  },
  {
    slug: "consumer_pets",
    canonicalName: "Pet Purchase and Vet Disputes",
    matcherSlug: "commercial",
    aliases: [
      "puppy scam",
      "pet purchase dispute",
      "vet negligence consumer",
      "faulty pet sale",
    ],
    userPhrases: [
      "puppy farm scam",
      "sick puppy bought",
      "pet shop sold unhealthy dog",
      "vet bill dispute",
      "pet insurance won't pay",
      "breeder won't help",
      "Lucy's Law",
    ],
    subIssues: [
      "Pet sales",
      "Vet bills",
      "Pet insurance",
      "Breeder disputes",
    ],
    relatedPracticeAreas: ["Consumer goods", "Insurance"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Was the pet bought from a breeder, shop, or private seller — and is it a health or cost dispute?",
    ],
    searchBoostTerms: [
      "pet purchase",
      "puppy",
      "Lucy's Law",
      "vet bill",
      "pet insurance",
    ],
  },
  {
    slug: "consumer_doorstep_cold_calling",
    canonicalName: "Doorstep Selling and Cold Calling",
    matcherSlug: "commercial",
    aliases: [
      "cold calling",
      "doorstep sales",
      "unsolicited calls",
      "pressure selling",
    ],
    userPhrases: [
      "sold something at the door",
      "cold caller mis-sold",
      "pressure selling at home",
      "cancel doorstep contract",
      "double glazing mis-sold",
      "solar panels mis-sold",
      "insulation scam",
      "cancel within 14 days doorstep",
    ],
    subIssues: [
      "Cancellation rights",
      "Mis-selling at home",
      "Solar and home improvements",
      "TPS and marketing calls",
    ],
    relatedPracticeAreas: ["Consumer services", "Energy", "Scams"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Was the sale at your home, and how many days ago was it?",
    ],
    searchBoostTerms: [
      "doorstep selling",
      "Consumer Contracts Regulations",
      "cooling off home",
      "cold calling",
      "TPS",
    ],
  },
  {
    slug: "consumer_small_claims",
    canonicalName: "Small Claims and County Court",
    matcherSlug: "commercial",
    aliases: [
      "small claims court",
      "money claim online",
      "MCOL",
      "county court claim",
    ],
    userPhrases: [
      "take someone to small claims",
      "money claim online",
      "sue a company",
      "county court claim consumer",
      "CCJ against company",
      "enforce judgment",
      "bailiff consumer debt",
    ],
    subIssues: [
      "Money Claim Online",
      "Court fees",
      "Enforcement",
      "Defendant response",
    ],
    relatedPracticeAreas: ["Consumer law", "Debt"],
    emergencySignals: ["court deadline"],
    legalAidLikely: false,
    clarificationQuestions: [
      "How much are you claiming, and have you already tried the company's complaints process?",
    ],
    searchBoostTerms: [
      "small claims",
      "Money Claim Online",
      "MCOL",
      "county court",
      "Part 7 claim",
    ],
  },
  {
    slug: "consumer_nursery_childcare",
    canonicalName: "Nursery and Childcare Fees",
    matcherSlug: "commercial",
    aliases: [
      "nursery fees",
      "childcare deposit",
      "nursery contract",
      "childminder dispute",
    ],
    userPhrases: [
      "nursery won't refund deposit",
      "childcare fees dispute",
      "nursery closed suddenly",
      "childminder complaint",
      "free childcare hours wrong",
      "tax free childcare problem",
      "after school club fees",
    ],
    subIssues: ["Deposits", "Closure", "Funding hours", "Contracts", "Safeguarding referrals"],
    relatedPracticeAreas: ["Consumer services", "Education"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about fees, a deposit, funded hours, or the nursery closing?",
    ],
    searchBoostTerms: ["nursery fees", "childcare", "Tax-Free Childcare", "deposit nursery"],
  },
  {
    slug: "consumer_private_healthcare",
    canonicalName: "Private Healthcare Billing",
    matcherSlug: "commercial",
    aliases: [
      "private hospital bill",
      "dentist overcharged",
      "cosmetic surgery dispute",
      "private treatment cost",
    ],
    userPhrases: [
      "private dentist bill too high",
      "hospital overcharged me",
      "cosmetic surgery gone wrong billing",
      "private healthcare refund",
      "treatment not covered insurance",
      "Bupa dispute",
      "Spire hospital complaint",
    ],
    subIssues: ["Billing disputes", "Insurance shortfall", "Cancellation", "Package deals"],
    relatedPracticeAreas: ["Clinical negligence", "Insurance", "Consumer services"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about the cost of treatment, insurance cover, or the quality of care?",
    ],
    searchBoostTerms: ["private healthcare", "dentist bill", "cosmetic surgery", "Bupa", "medical billing"],
  },
  {
    slug: "consumer_property_repairs_tenant",
    canonicalName: "Tenant Contents and Deposit Damage",
    matcherSlug: "housing",
    aliases: [
      "unfair deposit deduction",
      "landlord damage claim",
      "inventory dispute",
    ],
    userPhrases: [
      "landlord keeping deposit unfairly",
      "charged for normal wear and tear",
      "inventory dispute deposit",
      "deductions from tenancy deposit",
      "my deposit dispute",
      "TDS dispute",
      "DPS dispute",
    ],
    subIssues: ["Deposit schemes", "Inventory", "Cleaning charges", "Damage claims"],
    relatedPracticeAreas: ["Housing", "Consumer law"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Which deposit scheme holds your deposit, and what deductions were made?",
    ],
    searchBoostTerms: [
      "tenancy deposit",
      "deposit deduction",
      "TDS",
      "DPS",
      "MyDeposits",
      "wear and tear",
    ],
  },
];
