import type { LegalIssueTaxonomyEntry } from "@/lib/legal/legal-issue-taxonomy-data";

/**
 * Additional UK practice areas beyond the core citizen-facing set.
 * Merged into LEGAL_ISSUE_TAXONOMY for directory + natural-language matching.
 */
export const LEGAL_ISSUE_TAXONOMY_EXTENDED: LegalIssueTaxonomyEntry[] = [
  {
    slug: "human_rights",
    canonicalName: "Human Rights",
    matcherSlug: "family",
    aliases: ["human rights law", "civil liberties", "ECHR", "European Convention"],
    userPhrases: [
      "human rights lawyer",
      "human rights solicitor",
      "civil liberties lawyer",
      "rights under the law",
    ],
    subIssues: ["ECHR claims", "Public authority duties", "Discrimination", "Detention"],
    relatedPracticeAreas: ["Public law", "Immigration", "Criminal Defence"],
    emergencySignals: ["detained", "removal imminent"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a public body decision, detention, discrimination, or an immigration/housing rights issue?",
    ],
    searchBoostTerms: ["human rights", "civil liberties", "ECHR", "public authority", "HRA 1998"],
  },
  {
    slug: "judicial_review",
    canonicalName: "Judicial Review",
    matcherSlug: "family",
    aliases: ["JR", "administrative law", "challenge a decision"],
    userPhrases: [
      "judicial review solicitor",
      "challenge council decision",
      "challenge government decision",
      "unlawful decision",
    ],
    subIssues: ["Pre-action protocol", "Permission stage", "Remedies", "Costs"],
    relatedPracticeAreas: ["Public law", "Housing", "Immigration", "Planning"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Which decision or public body are you trying to challenge, and is there a deadline?",
    ],
    searchBoostTerms: ["judicial review", "JR", "administrative law", "public law", "unlawful"],
  },
  {
    slug: "motoring_offences",
    canonicalName: "Motoring Offences",
    matcherSlug: "criminal_defence",
    aliases: ["driving offences", "road traffic law", "traffic offence", "motoring law"],
    userPhrases: [
      "motoring solicitor",
      "driving ban",
      "speeding offence",
      "drink driving",
      "dangerous driving",
      "disqualified from driving",
      "totting up",
      "penalty points",
    ],
    subIssues: ["Speeding", "Drink/drug driving", "Dangerous driving", "Bans and appeals"],
    relatedPracticeAreas: ["Criminal Defence", "Parking and PCNs"],
    emergencySignals: ["court tomorrow", "driving ban imminent"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about speeding, drink/drug driving, a driving ban, or another traffic offence?",
    ],
    searchBoostTerms: [
      "motoring offence",
      "road traffic",
      "driving ban",
      "speeding",
      "drink driving",
      "DVLA",
      "magistrates",
    ],
  },
  {
    slug: "planning_law",
    canonicalName: "Planning Law",
    matcherSlug: "commercial",
    aliases: ["planning permission", "planning appeal", "town and country planning"],
    userPhrases: [
      "planning solicitor",
      "planning permission refused",
      "planning appeal",
      "enforcement notice",
      "listed building",
    ],
    subIssues: ["Applications", "Appeals", "Enforcement", "Compulsory purchase"],
    relatedPracticeAreas: ["Public law", "Environmental law", "Commercial property"],
    emergencySignals: ["enforcement notice deadline"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a planning application, refusal, enforcement notice, or appeal?",
    ],
    searchBoostTerms: ["planning law", "planning permission", "LPA", "enforcement", "PINS appeal"],
  },
  {
    slug: "intellectual_property",
    canonicalName: "Intellectual Property",
    matcherSlug: "commercial",
    aliases: ["IP law", "patents", "trademarks", "trade marks", "copyright"],
    userPhrases: [
      "IP solicitor",
      "trademark dispute",
      "patent lawyer",
      "copyright infringement",
      "brand protection",
    ],
    subIssues: ["Trade marks", "Copyright", "Patents", "Design rights", "Licensing"],
    relatedPracticeAreas: ["Commercial law", "Media and defamation"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about trade marks, copyright, patents, or another IP right?",
    ],
    searchBoostTerms: ["intellectual property", "trademark", "copyright", "patent", "IP infringement"],
  },
  {
    slug: "fraud_financial_crime",
    canonicalName: "Fraud and Financial Crime",
    matcherSlug: "criminal_defence",
    aliases: ["financial crime", "white collar crime", "money laundering", "SFO investigation"],
    userPhrases: [
      "fraud solicitor",
      "accused of fraud",
      "financial crime lawyer",
      "money laundering investigation",
      "SFO",
    ],
    subIssues: ["Fraud", "Money laundering", "Insider dealing", "Regulatory investigations"],
    relatedPracticeAreas: ["Criminal Defence", "Commercial law"],
    emergencySignals: ["arrested", "interview under caution", "raid"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this a police/regulator investigation, charge, or business compliance issue?",
    ],
    searchBoostTerms: ["fraud", "financial crime", "money laundering", "SFO", "FCA investigation"],
  },
  {
    slug: "tax_law",
    canonicalName: "Tax Law",
    matcherSlug: "commercial",
    aliases: ["tax advice", "HMRC dispute", "tax tribunal"],
    userPhrases: [
      "tax solicitor",
      "HMRC investigation",
      "HMRC tax investigation",
      "tax dispute",
      "inheritance tax",
      "capital gains tax",
      "VAT dispute",
    ],
    subIssues: ["Personal tax", "Corporate tax", "VAT", "Inheritance tax", "Tribunal appeals"],
    relatedPracticeAreas: ["Wills and probate", "Commercial law"],
    emergencySignals: ["HMRC deadline"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about personal tax, business/VAT, inheritance tax, or an HMRC dispute?",
    ],
    searchBoostTerms: ["tax law", "HMRC", "tax tribunal", "VAT", "inheritance tax", "tax investigation"],
  },
  {
    slug: "insolvency",
    canonicalName: "Insolvency",
    matcherSlug: "commercial",
    aliases: ["liquidation", "administration", "company insolvency"],
    userPhrases: [
      "insolvency solicitor",
      "company liquidation",
      "creditors winding up",
      "administration order",
      "director disqualification",
    ],
    subIssues: ["Liquidation", "Administration", "CVAs", "Director duties"],
    relatedPracticeAreas: ["Debt", "Commercial law"],
    emergencySignals: ["winding up petition"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about personal insolvency, a company liquidation, or director liability?",
    ],
    searchBoostTerms: ["insolvency", "liquidation", "winding up", "administration", "IVA"],
  },
  {
    slug: "commercial_property",
    canonicalName: "Commercial Property",
    matcherSlug: "commercial",
    aliases: ["business property", "commercial lease", "property development"],
    userPhrases: [
      "commercial property solicitor",
      "business lease",
      "commercial lease dispute",
      "property development lawyer",
    ],
    subIssues: ["Leases", "Development", "Licences", "Rent reviews"],
    relatedPracticeAreas: ["Conveyancing", "Planning law"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a commercial lease, purchase/sale, or development?",
    ],
    searchBoostTerms: ["commercial property", "business lease", "commercial lease", "landlord commercial"],
  },
  {
    slug: "construction_law",
    canonicalName: "Construction Law",
    matcherSlug: "commercial",
    aliases: ["building dispute", "construction contract", "JCT", "NEC"],
    userPhrases: [
      "construction solicitor",
      "building contract dispute",
      "defective building work",
      "snagging dispute",
      "contractor dispute",
    ],
    subIssues: ["Defects", "Delay claims", "Adjudication", "Professional negligence"],
    relatedPracticeAreas: ["Commercial law", "Commercial property"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about defective works, payment disputes, or a contract termination?",
    ],
    searchBoostTerms: ["construction law", "building dispute", "adjudication", "JCT", "defective works"],
  },
  {
    slug: "defamation_media",
    canonicalName: "Defamation and Media Law",
    matcherSlug: "commercial",
    aliases: ["libel", "slander", "reputation management", "press law"],
    userPhrases: [
      "defamation solicitor",
      "libel lawyer",
      "someone defamed me",
      "false allegations online",
      "reputation damage",
    ],
    subIssues: ["Libel", "Slander", "Injunctions", "Online harassment"],
    relatedPracticeAreas: ["Privacy", "Employment"],
    emergencySignals: ["publication imminent"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about something published about you, online posts, or a media organisation?",
    ],
    searchBoostTerms: ["defamation", "libel", "slander", "reputation", "media law"],
  },
  {
    slug: "data_protection",
    canonicalName: "Data Protection and Privacy",
    matcherSlug: "commercial",
    aliases: ["GDPR", "privacy law", "ICO complaint", "subject access request"],
    userPhrases: [
      "data protection lawyer",
      "GDPR breach",
      "privacy solicitor",
      "subject access request refused",
      "ICO",
    ],
    subIssues: ["SARs", "Breach response", "ICO complaints", "Employment data"],
    relatedPracticeAreas: ["Employment", "Commercial law"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a data breach, a subject access request, or a privacy complaint?",
    ],
    searchBoostTerms: ["data protection", "GDPR", "privacy", "ICO", "subject access request"],
  },
  {
    slug: "environmental_law",
    canonicalName: "Environmental Law",
    matcherSlug: "commercial",
    aliases: ["environmental regulation", "pollution", "EA enforcement"],
    userPhrases: [
      "environmental solicitor",
      "pollution notice",
      "Environment Agency",
      "contaminated land",
    ],
    subIssues: ["Permits", "Enforcement", "Nuisance", "Climate/regulatory"],
    relatedPracticeAreas: ["Planning law", "Public law"],
    emergencySignals: ["stop notice", "enforcement deadline"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a regulator notice, planning/environment overlap, or neighbour nuisance?",
    ],
    searchBoostTerms: ["environmental law", "pollution", "Environment Agency", "contaminated land"],
  },
  {
    slug: "inquests_coroners",
    canonicalName: "Inquests and Coroners",
    matcherSlug: "personal_injury",
    aliases: ["coroner's court", "coroner inquest", "Article 2 inquest"],
    userPhrases: [
      "inquest solicitor",
      "coroner inquest",
      "death in custody lawyer",
      "represented at inquest",
    ],
    subIssues: ["Article 2", "Prevention of future deaths", "Interested person"],
    relatedPracticeAreas: ["Clinical negligence", "Personal injury"],
    emergencySignals: ["inquest hearing soon"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is the inquest about a death in custody/care, medical treatment, or another context?",
    ],
    searchBoostTerms: ["inquest", "coroner", "Article 2", "PFD report"],
  },
  {
    slug: "charity_law",
    canonicalName: "Charity Law",
    matcherSlug: "commercial",
    aliases: ["charities", "trustee duties", "Charity Commission"],
    userPhrases: ["charity solicitor", "trustee dispute", "Charity Commission investigation"],
    subIssues: ["Governance", "Regulatory", "Mergers", "Trading subsidiaries"],
    relatedPracticeAreas: ["Commercial law", "Wills and trusts"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about charity governance, a regulatory investigation, or a merger?",
    ],
    searchBoostTerms: ["charity law", "trustee", "Charity Commission", "governance"],
  },
  {
    slug: "agricultural_rural",
    canonicalName: "Agricultural and Rural Law",
    matcherSlug: "commercial",
    aliases: ["farm law", "agricultural tenancy", "rural property"],
    userPhrases: [
      "agricultural solicitor",
      "farm tenancy dispute",
      "rural property lawyer",
      "Agricultural Holdings Act",
    ],
    subIssues: ["Farm tenancies", "Succession", "Rights of way", "Environment"],
    relatedPracticeAreas: ["Commercial property", "Planning law"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a farm tenancy, succession, or rural land dispute?",
    ],
    searchBoostTerms: ["agricultural law", "farm tenancy", "rural", "AHA 1986"],
  },
  {
    slug: "military_law",
    canonicalName: "Military Law",
    matcherSlug: "criminal_defence",
    aliases: ["court martial", "service law", "Armed Forces"],
    userPhrases: [
      "military lawyer",
      "court martial solicitor",
      "Armed Forces legal",
      "service complaint",
    ],
    subIssues: ["Court martial", "Service complaints", "Medical discharge"],
    relatedPracticeAreas: ["Criminal Defence", "Employment"],
    emergencySignals: ["court martial date"],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a court martial, service complaint, or discharge/medical issue?",
    ],
    searchBoostTerms: ["military law", "court martial", "Armed Forces", "service complaint"],
  },
  {
    slug: "maritime_law",
    canonicalName: "Maritime and Shipping Law",
    matcherSlug: "commercial",
    aliases: ["shipping law", "admiralty", "seafarer rights"],
    userPhrases: ["maritime solicitor", "shipping dispute", "seafarer wages", "admiralty claim"],
    subIssues: ["Cargo claims", "Collisions", "Seafarer employment", "Salvage"],
    relatedPracticeAreas: ["Commercial law", "Employment"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about cargo/shipping, seafarer employment, or an admiralty claim?",
    ],
    searchBoostTerms: ["maritime law", "shipping", "admiralty", "seafarer"],
  },
  {
    slug: "aviation_law",
    canonicalName: "Aviation Law",
    matcherSlug: "commercial",
    aliases: ["airline compensation", "flight delay claim", "CAA"],
    userPhrases: [
      "aviation solicitor",
      "flight compensation",
      "airline refused refund",
      "denied boarding",
    ],
    subIssues: ["EU261 claims", "Regulatory", "Leasing", "Accidents"],
    relatedPracticeAreas: ["Consumer law", "Personal injury"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about flight compensation, airline contracts, or an aviation accident?",
    ],
    searchBoostTerms: ["aviation law", "flight delay", "EU261", "airline compensation"],
  },
  {
    slug: "sports_law",
    canonicalName: "Sports Law",
    matcherSlug: "commercial",
    aliases: ["football contract", "athlete contract", "sports dispute"],
    userPhrases: [
      "sports solicitor",
      "football contract dispute",
      "agent dispute",
      "disciplinary hearing sport",
    ],
    subIssues: ["Contracts", "Disciplinary", "Regulatory", "Sponsorship"],
    relatedPracticeAreas: ["Employment", "Commercial law"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a player contract, disciplinary process, or commercial sponsorship?",
    ],
    searchBoostTerms: ["sports law", "football contract", "athlete", "disciplinary"],
  },
  {
    slug: "banking_finance",
    canonicalName: "Banking and Finance",
    matcherSlug: "commercial",
    aliases: ["finance law", "loan agreement", "secured lending"],
    userPhrases: [
      "banking solicitor",
      "loan dispute",
      "mortgage fraud",
      "finance lawyer",
    ],
    subIssues: ["Lending", "Security", "Derivatives", "Regulatory"],
    relatedPracticeAreas: ["Commercial law", "Debt"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a loan/mortgage dispute, business finance, or regulatory matter?",
    ],
    searchBoostTerms: ["banking and finance", "loan", "lending", "secured finance"],
  },
  {
    slug: "discrimination_equality",
    canonicalName: "Discrimination and Equality",
    matcherSlug: "employment",
    aliases: ["equality act", "protected characteristics", "discrimination claim"],
    userPhrases: [
      "discrimination lawyer",
      "discriminated against",
      "Equality Act",
      "race discrimination",
      "disability discrimination",
    ],
    subIssues: ["Race", "Sex", "Disability", "Age", "Religion"],
    relatedPracticeAreas: ["Employment", "Education", "Housing"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Where did the discrimination happen — work, housing, education, or services?",
    ],
    searchBoostTerms: ["discrimination", "Equality Act", "protected characteristic", "harassment"],
  },
];
