export type SubIssueRule = {
  label: string;
  anyTerms: string[];
  allTerms?: string[];
  excludeTerms?: string[];
};

export type LegalIssueTaxonomyEntry = {
  slug: string;
  canonicalName: string;
  matcherSlug: string;
  aliases: string[];
  userPhrases: string[];
  subIssues: string[];
  subIssueRules?: SubIssueRule[];
  relatedPracticeAreas: string[];
  emergencySignals: string[];
  legalAidLikely: boolean;
  clarificationQuestions: string[];
  searchBoostTerms: string[];
};

import { LEGAL_ISSUE_TAXONOMY_EXTENDED } from "@/lib/legal/legal-issue-taxonomy-extended";
import { LEGAL_ISSUE_TAXONOMY_CONSUMER } from "@/lib/legal/legal-issue-taxonomy-consumer";

/**
 * Canonical legal-issue taxonomy (UK directory / matcher).
 * `matcherSlug` maps to seeded `PracticeArea` rows where applicable.
 */
const LEGAL_ISSUE_TAXONOMY_CORE: LegalIssueTaxonomyEntry[] = [
  {
    slug: "prison_law",
    canonicalName: "Prison Law",
    matcherSlug: "criminal_defence",
    aliases: ["prison law", "prisoner rights", "prison legal"],
    userPhrases: [
      "prison lawyer",
      "lawyer for prison",
      "solicitor for someone in prison",
      "prison recall",
      "prison recall lawyer",
    ],
    subIssues: ["Parole", "Appeals", "Human rights in prison", "Licence recall", "Adjudications"],
    relatedPracticeAreas: ["Criminal Defence", "Appeals", "Parole", "Human Rights", "Legal Aid"],
    emergencySignals: ["recall to prison", "urgent parole", "imminent release"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about parole, recall to prison, prison conditions, an appeal, or a new criminal case?",
    ],
    searchBoostTerms: [
      "prison law",
      "prisoner rights",
      "parole board",
      "prison sentence",
      "appeal",
      "licence recall",
      "adjudication",
      "criminal solicitor",
      "police custody",
      "HMP",
    ],
  },
  {
    slug: "criminal_defence",
    canonicalName: "Criminal Defence",
    matcherSlug: "criminal_defence",
    aliases: ["crime", "defence lawyer", "criminal solicitor"],
    userPhrases: ["police issue", "arrested", "charged", "court case", "criminal case", "need a criminal lawyer"],
    subIssues: ["Police station", "Magistrates", "Crown Court", "Bail", "Investigation"],
    relatedPracticeAreas: ["Prison Law", "Appeals", "Motoring offences", "Fraud"],
    emergencySignals: ["arrested", "police station", "bail", "urgent", "tonight"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a police investigation, a first court hearing, sentencing, an appeal, or something else?",
    ],
    searchBoostTerms: [
      "criminal defence",
      "police station advice",
      "duty solicitor",
      "magistrates court",
      "crown court",
      "bail",
      "charge",
      "investigation",
      "CPS",
    ],
  },
  {
    slug: "employment",
    canonicalName: "Employment Law",
    matcherSlug: "employment",
    aliases: ["workplace law", "work law"],
    userPhrases: [
      "employment advice",
      "work problem",
      "unfair dismissal",
      "unfairly dismissed",
      "dismissed",
      "redundancy",
      "employment tribunal",
      "my employer",
      "employer",
      "unpaid commission",
      "unpaid wages",
      "commission",
      "wages",
      "salary",
      "holiday pay",
      "workplace dispute",
    ],
    subIssues: [
      "Unfair dismissal",
      "Discrimination",
      "Redundancy",
      "Settlement agreements",
      "Workplace grievances",
      "Unpaid wages",
      "Unpaid commission",
      "Holiday pay",
    ],
    subIssueRules: [
      {
        label: "unpaid commission",
        anyTerms: ["commission", "comission"],
        excludeTerms: ["universal credit", "benefits appeal"],
      },
      {
        label: "unpaid wages",
        anyTerms: ["wage", "wages", "salary"],
        allTerms: ["unpaid", "paid"],
        excludeTerms: ["universal credit"],
      },
      {
        label: "unpaid wages",
        anyTerms: ["unpaid wage", "unpaid wages", "not paid", "hasnt paid", "haven't paid", "hasn't paid"],
      },
      {
        label: "holiday pay",
        anyTerms: ["holiday pay"],
      },
      {
        label: "redundancy",
        anyTerms: ["redundan"],
      },
      {
        label: "unfair dismissal",
        anyTerms: ["dismiss", "fired", "sacked", "unfair dismissal"],
      },
      {
        label: "discrimination at work",
        anyTerms: ["discriminat"],
      },
      {
        label: "unpaid wages or pay dispute",
        anyTerms: ["employer", "boss", "workplace"],
        allTerms: ["pay", "paid"],
      },
    ],
    relatedPracticeAreas: ["Whistleblowing", "TUPE", "Restrictive covenants"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about dismissal, discrimination, redundancy, unpaid wages, a workplace grievance, or a settlement agreement?",
    ],
    searchBoostTerms: [
      "employment solicitor",
      "workplace dispute",
      "unfair dismissal",
      "redundancy",
      "discrimination at work",
      "settlement agreement",
      "employment tribunal",
      "ACAS",
      "grievance",
      "unpaid wages",
      "unpaid commission",
      "commission",
      "employer",
    ],
  },
  {
    slug: "immigration",
    canonicalName: "Immigration Law",
    matcherSlug: "immigration",
    aliases: ["immigration advice", "visa help"],
    userPhrases: [
      "help with immigration",
      "visa refused",
      "visa application",
      "spouse visa",
      "student visa",
      "asylum",
      "deportation",
      "indefinite leave to remain",
      "leave to remain",
      "home office decision",
      "immigration appeal",
    ],
    subIssues: ["Family visas", "Asylum", "Citizenship", "Appeals", "Student visas"],
    relatedPracticeAreas: ["Human rights", "EUSS", "Immigration tribunal"],
    emergencySignals: ["removal", "detention", "deportation imminent"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a visa application, asylum, settlement, an appeal, or a family immigration matter?",
    ],
    searchBoostTerms: [
      "immigration solicitor",
      "visa",
      "asylum",
      "indefinite leave",
      "spouse visa",
      "Home Office",
      "immigration tribunal",
    ],
  },
  {
    slug: "family",
    canonicalName: "Family Law",
    matcherSlug: "family",
    aliases: ["family matters", "relationship breakdown"],
    userPhrases: [
      "family lawyer",
      "family solicitor",
      "divorce",
      "children",
      "child custody",
      "child arrangements",
      "custody",
      "contact",
      "contact order",
      "child contact",
      "prenup",
      "prenuptial",
      "prenuptial agreement",
      "postnup",
      "cohabitation agreement",
      "co-parenting",
      "coparenting",
      "co-parent",
      "domestic abuse",
      "domestic violence",
      "abusive ex",
      "abusive partner",
      "non-molestation",
      "non molestation order",
    ],
    subIssues: [
      "Divorce",
      "Child arrangements",
      "Domestic abuse",
      "Financial remedies",
      "Care proceedings",
      "Prenuptial agreements",
      "Cohabitation agreements",
    ],
    subIssueRules: [
      {
        label: "prenuptial agreement",
        anyTerms: ["prenup", "prenuptial", "pre-nup", "postnup", "post-nup"],
      },
      {
        label: "cohabitation agreement",
        anyTerms: ["cohabitation agreement", "living together agreement", "cohabitation"],
      },
      {
        label: "domestic abuse",
        anyTerms: [
          "domestic abuse",
          "domestic violence",
          "abusive ex",
          "abusive partner",
          "non-molestation",
          "coercive control",
        ],
      },
      {
        label: "child arrangements",
        anyTerms: [
          "co-parent",
          "coparent",
          "co-parenting",
          "child arrangements",
          "contact order",
          "custody",
          "child contact",
          "contact arrangements",
          "contact order",
          "custody",
          "child contact",
        ],
      },
    ],
    relatedPracticeAreas: ["Mediation", "Injunctions"],
    emergencySignals: [
      "domestic violence",
      "domestic abuse",
      "child abduction",
      "urgent injunction",
      "threats to kill",
    ],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about divorce, child arrangements, domestic abuse, finances on separation, prenuptial or cohabitation agreements, or care proceedings?",
    ],
    searchBoostTerms: [
      "family solicitor",
      "divorce",
      "child arrangements",
      "child contact",
      "contact order",
      "financial remedy",
      "prenuptial agreement",
      "marriage",
      "CAFCASS",
      "domestic abuse",
      "co-parenting",
      "non-molestation",
    ],
  },
  {
    slug: "neighbour_dispute",
    canonicalName: "Neighbour Disputes",
    matcherSlug: "family",
    aliases: ["neighbour dispute", "boundary dispute", "noise nuisance", "anti-social behaviour"],
    userPhrases: [
      "noisy neighbour",
      "neighbour harassment",
      "boundary dispute",
      "anti-social neighbour",
      "neighbour loud noise",
      "loud noise from neighbour",
      "neighbour noise",
      "noise from neighbour",
      "fight with neighbour",
      "argument with neighbour",
      "neighbour keeps making noise",
      "neighbour over loud noise",
      "loud noise at night",
    ],
    subIssues: ["Noise nuisance", "Boundary disputes", "Harassment", "Anti-social behaviour"],
    relatedPracticeAreas: ["Public law", "Criminal Defence"],
    emergencySignals: ["threats from neighbour", "harassment tonight"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about noise, boundaries, anti-social behaviour, harassment, or a housing/tenancy issue?",
    ],
    searchBoostTerms: [
      "neighbour dispute",
      "noise nuisance",
      "boundary dispute",
      "anti-social behaviour",
      "ASB",
      "harassment",
      "injunction",
    ],
  },
  {
    slug: "housing",
    canonicalName: "Landlord and Tenant",
    matcherSlug: "housing",
    aliases: [
      "landlord tenant",
      "landlord and tenant",
      "renting",
      "tenancy",
      "private renting",
      "housing law",
    ],
    userPhrases: [
      "housing problem",
      "eviction",
      "eviction help",
      "disrepair",
      "section 21",
      "landlord kicking me out",
      "kicking me out tonight",
      "my landlord",
      "landlord won't",
      "landlord wont",
      "deposit not returned",
      "deposit dispute",
      "tenancy deposit",
      "return my deposit",
      "private landlord",
      "letting agent",
    ],
    subIssues: [
      "Deposit disputes",
      "Possession",
      "Eviction",
      "Housing disrepair",
      "Homelessness",
      "Anti-social behaviour",
      "Neighbour dispute",
    ],
    subIssueRules: [
      { label: "deposit dispute", anyTerms: ["deposit", "tenancy deposit", "holding deposit", "bond"] },
      {
        label: "eviction or possession",
        anyTerms: ["eviction", "section 21", "section 8", "possession", "kicking me out", "notice to quit"],
      },
      { label: "housing disrepair", anyTerms: ["disrepair", "damp", "mould", "mold", "repair", "leak", "unsafe"] },
      { label: "homelessness", anyTerms: ["homeless", "homelessness"] },
      { label: "neighbour dispute", anyTerms: ["neighbour", "asb", "anti-social", "harassment"] },
      { label: "landlord and tenant", anyTerms: ["landlord", "tenant", "renting", "tenancy", "letting"] },
    ],
    relatedPracticeAreas: [
      "Landlord and tenant",
      "Housing disrepair",
      "Deposit disputes",
      "Possession",
    ],
    emergencySignals: ["homeless tonight", "illegal eviction now", "kicking me out tonight"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about eviction, repairs, a deposit, homelessness risk, or a neighbour dispute?",
    ],
    searchBoostTerms: [
      "housing solicitor",
      "landlord and tenant",
      "eviction",
      "landlord",
      "tenant",
      "tenancy deposit",
      "deposit",
      "section 21",
      "section 8",
      "disrepair",
      "possession",
    ],
  },
  {
    slug: "welfare_benefits",
    canonicalName: "Welfare Benefits",
    matcherSlug: "family",
    aliases: ["benefits", "PIP", "UC", "universal credit"],
    userPhrases: [
      "benefits appeal",
      "mandatory reconsideration",
      "PIP appeal",
      "ESA",
      "legal aid",
      "need legal aid",
      "legal aid help",
    ],
    subIssues: ["PIP", "Universal Credit", "Housing benefit", "ESA", "DLA", "Overpayments"],
    relatedPracticeAreas: ["Community care", "Debt", "Housing"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Which benefit is involved (PIP, Universal Credit, ESA, housing benefit, or another), and is it a new claim, reconsideration, or tribunal appeal?",
    ],
    searchBoostTerms: [
      "benefits tribunal",
      "mandatory reconsideration",
      "PIP appeal",
      "universal credit",
      "welfare rights",
      "social security",
    ],
  },
  {
    slug: "personal_injury",
    canonicalName: "Personal Injury",
    matcherSlug: "personal_injury",
    aliases: ["injury claim", "accident claim"],
    userPhrases: ["injured in an accident", "RTA", "trip slip"],
    subIssues: ["Road traffic", "Employers liability", "Public liability", "Fatal claims"],
    relatedPracticeAreas: ["Clinical negligence"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Was this a road accident, an accident at work, a public place injury, or medical treatment gone wrong?",
    ],
    searchBoostTerms: [
      "personal injury",
      "compensation claim",
      "RTA",
      "road traffic accident",
      "employers liability",
      "CNF",
    ],
  },
  {
    slug: "clinical_negligence",
    canonicalName: "Clinical Negligence",
    matcherSlug: "personal_injury",
    aliases: ["medical negligence", "NHS negligence"],
    userPhrases: [
      "surgical error",
      "misdiagnosis claim",
      "hospital negligence",
      "doctor made a mistake",
    ],
    subIssues: ["Surgery", "Birth injury", "Misdiagnosis", "Consent"],
    relatedPracticeAreas: ["Personal injury", "Inquests"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about NHS treatment, private healthcare, a birth injury, or a fatal incident?",
    ],
    searchBoostTerms: [
      "clinical negligence",
      "medical negligence",
      "NHS claim",
      "Bolt Burdon Kemp style",
      "CQC",
    ],
  },
  {
    slug: "wills_probate",
    canonicalName: "Wills and Probate",
    matcherSlug: "family",
    aliases: ["probate", "estate planning"],
    userPhrases: ["will writing", "probate after death", "executor", "LPA"],
    subIssues: ["Wills", "Probate", "Estates", "Trusts", "LPA", "Inheritance disputes"],
    relatedPracticeAreas: ["Tax", "Contentious probate"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about making a will, administering an estate after death, a trust, lasting powers of attorney, or a dispute over inheritance?",
    ],
    searchBoostTerms: [
      "wills and probate",
      "probate solicitor",
      "executor",
      "lasting power of attorney",
      "LPA",
      "estate administration",
    ],
  },
  {
    slug: "conveyancing",
    canonicalName: "Conveyancing",
    matcherSlug: "conveyancing",
    aliases: [
      "conveyancer",
      "property lawyer",
      "residential property",
      "house purchase",
      "house sale",
      "first time buyer",
      "first-time buyer",
      "FTB",
    ],
    userPhrases: [
      "conveyancing solicitor",
      "conveyancing lawyer",
      "buying a house",
      "buying a flat",
      "buying my first home",
      "first time buyer",
      "first-time buyer",
      "selling a house",
      "property purchase",
      "estate agent misrepresentation",
      "estate agent lied",
      "flat for sale cash only",
      "building due to be demolished",
      "cladding issues flat",
      "misrepresenting property sale",
      "remortgage",
      "transfer of equity",
      "need a conveyancer",
    ],
    subIssues: ["Purchase", "Sale", "Remortgage", "Leasehold", "Transfer of equity"],
    subIssueRules: [
      {
        label: "Purchase",
        anyTerms: ["buy", "buying", "purchase", "first time buyer", "first-time buyer", "ftb"],
        excludeTerms: ["sell", "selling"],
      },
      {
        label: "Sale",
        anyTerms: ["sell", "selling", "sale of property", "house sale"],
        excludeTerms: ["buy", "buying"],
      },
      {
        label: "Remortgage",
        anyTerms: ["remortgage", "re-mortgage", "refinance"],
      },
      {
        label: "Leasehold",
        anyTerms: ["leasehold", "service charge", "ground rent", "lease extension"],
      },
      {
        label: "Transfer of equity",
        anyTerms: ["transfer of equity", "add name to title", "remove name from title"],
      },
    ],
    relatedPracticeAreas: ["Residential conveyancing", "Landlord and tenant"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this for buying, selling, remortgaging, or transferring a share in a property?",
    ],
    searchBoostTerms: [
      "conveyancing",
      "residential conveyancing",
      "property purchase",
      "property misrepresentation",
      "buying and selling a home",
      "estate agent",
      "house sale",
      "first time buyer",
      "remortgage",
      "transfer of equity",
      "conveyancing solicitor",
    ],
  },
  {
    slug: "commercial",
    canonicalName: "Commercial Law",
    matcherSlug: "commercial",
    aliases: ["business law", "company law"],
    userPhrases: ["commercial contract", "shareholder dispute", "B2B"],
    subIssues: ["Contracts", "Shareholders", "Partnerships", "Debt recovery"],
    relatedPracticeAreas: ["Employment", "Insolvency"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a contract dispute, a shareholder or partnership issue, unpaid invoices, or something else?",
    ],
    searchBoostTerms: [
      "commercial solicitor",
      "breach of contract",
      "shareholder dispute",
      "debt recovery",
      "B2B",
    ],
  },
  {
    slug: "parking_pcn",
    canonicalName: "Parking and PCNs",
    matcherSlug: "criminal_defence",
    aliases: [
      "parking fine",
      "penalty charge notice",
      "PCN",
      "PCNs",
      "civil parking enforcement",
      "parking regulations",
      "London tribunal",
      "London Tribunals",
    ],
    userPhrases: [
      "parking ticket",
      "parking PCN",
      "council parking fine",
      "parking ticket appeal",
      "parking regulations",
      "private parking charge",
      "parking enforcement",
      "decriminalised parking",
      "council PCN",
      "Hounslow PCN",
      "permit road",
      "restricted road",
      "appeal the other PCNs",
      "multiple PCNs",
    ],
    subIssues: [
      "Council PCN appeals",
      "Private parking charges",
      "Permit zones",
      "Double yellow lines",
      "Traffic regulation orders",
    ],
    relatedPracticeAreas: ["Motoring offences", "Consumer", "Public law"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this a council PCN, a private parking charge, a permit or zone issue, or a motoring offence?",
    ],
    searchBoostTerms: [
      "parking PCN",
      "penalty charge notice",
      "parking fine appeal",
      "council parking",
      "parking ticket",
      "civil parking enforcement",
      "private parking charge",
      "traffic management order",
      "parking regulations",
      "appealing a parking ticket",
      "London Tribunals",
      "when to appeal a parking ticket",
    ],
  },
  {
    slug: "consumer",
    canonicalName: "Consumer Law",
    matcherSlug: "commercial",
    aliases: [
      "consumer rights",
      "consumer protection",
      "consumer dispute",
      "trader complaint",
      "retailer complaint",
      "Citizens Advice consumer",
      "Citizens Advice",
      "Trading Standards",
      "Citizens Advice consumer service",
    ],
    userPhrases: [
      "consumer rights",
      "consumer advice",
      "consumer solicitor",
      "consumer lawyer",
      "refund",
      "trader dispute",
      "Section 75",
      "section 75 claim",
      "faulty goods",
      "poor service",
      "company won't help",
      "complaint ignored",
      "ombudsman complaint",
      "Consumer Rights Act",
      "unfair contract",
      "misleading advert",
      "false advertising",
      "cooling off period",
      "chargeback",
      "customs",
      "customs seizure",
      "import duty",
      "import tax",
      "bringing goods into the UK",
      "bringing goods into England",
      "importing from abroad",
      "hmrc customs",
      "excise",
      "border force seizure",
    ],
    subIssues: [
      "Goods and refunds",
      "Services and traders",
      "Travel and holidays",
      "Finance and credit",
      "Utilities and telecoms",
      "Online shopping",
      "Insurance",
      "Subscriptions",
      "Small claims",
      "Customs and imports",
    ],
    subIssueRules: [
      {
        label: "customs and imports",
        anyTerms: [
          "customs",
          "import duty",
          "import tax",
          "excise",
          "hmrc",
          "border force",
          "bringing into england",
          "bringing into the uk",
          "importing from",
          "fly from",
        ],
      },
    ],
    relatedPracticeAreas: [
      "Debt",
      "Small claims",
      "Housing",
      "Travel",
      "Energy and utilities",
    ],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about faulty goods, poor services, a holiday or travel issue, finance, utilities, or something bought online?",
    ],
    searchBoostTerms: [
      "consumer law",
      "consumer rights",
      "Consumer Rights Act",
      "faulty goods",
      "trader",
      "retailer",
      "small claims",
      "ombudsman",
      "Financial Ombudsman",
      "Trading Standards",
      "Citizens Advice",
      "chargeback",
      "refund",
      "mis-selling",
      "customs",
      "import duty",
      "HMRC",
      "border force",
    ],
  },
  {
    slug: "debt",
    canonicalName: "Debt",
    matcherSlug: "commercial",
    aliases: ["debt advice", "bailiffs", "CCJ"],
    userPhrases: ["debt problem", "can't pay creditors", "bankruptcy"],
    subIssues: ["CCJ", "Bailiffs", "IVA", "Bankruptcy", "Council tax arrears"],
    relatedPracticeAreas: ["Housing", "Consumer"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about credit cards or loans, council tax, rent arrears, bailiffs, or insolvency options (IVA/bankruptcy)?",
    ],
    searchBoostTerms: ["debt advice", "CCJ", "bailiff", "StepChange", "IVA", "bankruptcy", "creditor"],
  },
  {
    slug: "education",
    canonicalName: "Education Law",
    matcherSlug: "family",
    aliases: ["school law", "SEN"],
    userPhrases: [
      "school exclusion",
      "child excluded from school",
      "excluded from school",
      "EHCP",
      "SEN appeal",
    ],
    subIssues: ["Exclusions", "EHCP", "Disability discrimination at school", "Higher education"],
    relatedPracticeAreas: ["Public law", "Discrimination"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a school exclusion, an EHCP or SEN support, disability discrimination, or a university issue?",
    ],
    searchBoostTerms: ["education law", "EHCP", "SEN", "school exclusion", "First-tier Tribunal SENDIST"],
  },
  {
    slug: "community_care",
    canonicalName: "Community Care",
    matcherSlug: "family",
    aliases: ["social care", "care needs"],
    userPhrases: ["care package", "NHS continuing healthcare", "local authority care"],
    subIssues: ["Care assessments", "CHC", "Care home disputes", "Direct payments"],
    relatedPracticeAreas: ["Mental health law", "Housing"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a care needs assessment, NHS continuing healthcare, a care home placement, or funding disputes?",
    ],
    searchBoostTerms: ["community care", "care act", "CHC", "social services", "care package"],
  },
  {
    slug: "mental_health",
    canonicalName: "Mental Health Law",
    matcherSlug: "family",
    aliases: ["MHA", "sectioning"],
    userPhrases: ["Mental Health Act", "sectioned", "tribunal mental health"],
    subIssues: ["Hospital detention", "Community treatment orders", "Nearest relative"],
    relatedPracticeAreas: ["Community care", "Capacity"],
    emergencySignals: ["sectioned", "MHA urgent"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about detention under the Mental Health Act, a tribunal, a community treatment order, or capacity and best interests?",
    ],
    searchBoostTerms: ["mental health tribunal", "MHA", "section 2", "section 3", "nearest relative"],
  },
  {
    slug: "public_law",
    canonicalName: "Public Law and Judicial Review",
    matcherSlug: "family",
    aliases: ["judicial review", "JR"],
    userPhrases: ["judicial review", "challenge council decision", "public authority"],
    subIssues: ["JR", "Human rights", "Data/GDPR public sector", "Planning judicial review"],
    relatedPracticeAreas: ["Housing", "Immigration", "Community care"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Which public body or decision is involved (local authority, government department, regulator, or court/tribunal process)?",
    ],
    searchBoostTerms: ["judicial review", "public law", "JR", "unlawful decision", "Crown Court challenge"],
  },
];

/** Core + extended + consumer practice areas for natural-language identification. */
export const LEGAL_ISSUE_TAXONOMY: LegalIssueTaxonomyEntry[] = [
  ...LEGAL_ISSUE_TAXONOMY_CORE,
  ...LEGAL_ISSUE_TAXONOMY_EXTENDED.filter(
    (ext) => !LEGAL_ISSUE_TAXONOMY_CORE.some((core) => core.slug === ext.slug),
  ),
  ...LEGAL_ISSUE_TAXONOMY_CONSUMER.filter(
    (c) =>
      !LEGAL_ISSUE_TAXONOMY_CORE.some((core) => core.slug === c.slug) &&
      !LEGAL_ISSUE_TAXONOMY_EXTENDED.some((ext) => ext.slug === c.slug),
  ),
];
