export type LegalIssueTaxonomyEntry = {
  slug: string;
  canonicalName: string;
  matcherSlug: string;
  aliases: string[];
  userPhrases: string[];
  subIssues: string[];
  relatedPracticeAreas: string[];
  emergencySignals: string[];
  legalAidLikely: boolean;
  clarificationQuestions: string[];
  searchBoostTerms: string[];
};

/**
 * Canonical legal-issue taxonomy (UK directory / matcher).
 * `matcherSlug` maps to seeded `PracticeArea` rows where applicable.
 */
export const LEGAL_ISSUE_TAXONOMY: LegalIssueTaxonomyEntry[] = [
  {
    slug: "prison_law",
    canonicalName: "Prison Law",
    matcherSlug: "criminal_defence",
    aliases: ["prison law", "prisoner rights", "prison legal"],
    userPhrases: ["prison lawyer", "lawyer for prison", "solicitor for someone in prison"],
    subIssues: ["Parole", "Appeals", "Human rights in prison", "Licence recall", "Adjudications"],
    relatedPracticeAreas: ["Criminal Defence", "Appeals", "Parole", "Human Rights", "Legal Aid"],
    emergencySignals: ["recall to prison", "urgent parole", "imminent release"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about parole, recall to prison, prison conditions, an appeal, or a new criminal case?",
    ],
    searchBoostTerms: [
      "prison law",
      "prisoner rights",
      "parole board",
      "prison sentence",
      "appeal",
      "licence recall",
      "adjudication",
      "criminal solicitor",
      "police custody",
      "HMP",
    ],
  },
  {
    slug: "criminal_defence",
    canonicalName: "Criminal Defence",
    matcherSlug: "criminal_defence",
    aliases: ["crime", "defence lawyer", "criminal solicitor"],
    userPhrases: ["police issue", "arrested", "charged", "court case", "criminal case", "need a criminal lawyer"],
    subIssues: ["Police station", "Magistrates", "Crown Court", "Bail", "Investigation"],
    relatedPracticeAreas: ["Prison Law", "Appeals", "Motoring offences", "Fraud"],
    emergencySignals: ["arrested", "police station", "bail", "urgent", "tonight"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a police investigation, a first court hearing, sentencing, an appeal, or something else?",
    ],
    searchBoostTerms: [
      "criminal defence",
      "police station advice",
      "duty solicitor",
      "magistrates court",
      "crown court",
      "bail",
      "charge",
      "investigation",
      "CPS",
    ],
  },
  {
    slug: "employment",
    canonicalName: "Employment Law",
    matcherSlug: "employment",
    aliases: ["workplace law", "work law"],
    userPhrases: [
      "employment advice",
      "work problem",
      "unfair dismissal",
      "unfairly dismissed",
      "dismissed",
      "redundancy",
      "tribunal",
    ],
    subIssues: [
      "Unfair dismissal",
      "Discrimination",
      "Redundancy",
      "Settlement agreements",
      "Workplace grievances",
      "Unpaid wages",
    ],
    relatedPracticeAreas: ["Whistleblowing", "TUPE", "Restrictive covenants"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about dismissal, discrimination, redundancy, unpaid wages, a workplace grievance, or a settlement agreement?",
    ],
    searchBoostTerms: [
      "employment solicitor",
      "workplace dispute",
      "unfair dismissal",
      "redundancy",
      "discrimination at work",
      "settlement agreement",
      "employment tribunal",
      "ACAS",
      "grievance",
    ],
  },
  {
    slug: "immigration",
    canonicalName: "Immigration Law",
    matcherSlug: "immigration",
    aliases: ["immigration advice", "visa help"],
    userPhrases: ["help with immigration", "visa", "asylum", "deportation", "settlement"],
    subIssues: ["Family visas", "Asylum", "Citizenship", "Appeals", "Student visas"],
    relatedPracticeAreas: ["Human rights", "EUSS", "Immigration tribunal"],
    emergencySignals: ["removal", "detention", "deportation imminent"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a visa application, asylum, settlement, an appeal, or a family immigration matter?",
    ],
    searchBoostTerms: [
      "immigration solicitor",
      "visa",
      "asylum",
      "indefinite leave",
      "spouse visa",
      "Home Office",
      "immigration tribunal",
    ],
  },
  {
    slug: "family",
    canonicalName: "Family Law",
    matcherSlug: "family",
    aliases: ["family matters", "relationship breakdown"],
    userPhrases: [
      "family lawyer",
      "family solicitor",
      "divorce",
      "children",
      "child custody",
      "child arrangements",
      "custody",
      "contact",
    ],
    subIssues: ["Divorce", "Child arrangements", "Domestic abuse", "Financial remedies", "Care proceedings"],
    relatedPracticeAreas: ["Mediation", "Injunctions"],
    emergencySignals: ["domestic violence", "child abduction", "urgent injunction"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about divorce, child arrangements, domestic abuse, finances on separation, or care proceedings?",
    ],
    searchBoostTerms: [
      "family solicitor",
      "divorce",
      "child arrangements",
      "contact order",
      "financial remedy",
      "CAFCASS",
    ],
  },
  {
    slug: "housing",
    canonicalName: "Housing Law",
    matcherSlug: "family",
    aliases: ["landlord tenant", "renting"],
    userPhrases: ["housing problem", "eviction", "disrepair", "section 21"],
    subIssues: ["Possession", "Deposit disputes", "Homelessness", "Anti-social behaviour"],
    relatedPracticeAreas: ["Community care", "Public law"],
    emergencySignals: ["homeless tonight", "illegal eviction now"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about eviction, repairs, a deposit, homelessness risk, or a neighbour dispute?",
    ],
    searchBoostTerms: [
      "housing solicitor",
      "eviction",
      "landlord",
      "tenant",
      "section 21",
      "section 8",
      "disrepair",
      "possession",
    ],
  },
  {
    slug: "welfare_benefits",
    canonicalName: "Welfare Benefits",
    matcherSlug: "family",
    aliases: ["benefits", "PIP", "UC", "universal credit"],
    userPhrases: [
      "benefits appeal",
      "mandatory reconsideration",
      "PIP appeal",
      "ESA",
      "legal aid",
      "need legal aid",
      "legal aid help",
    ],
    subIssues: ["PIP", "Universal Credit", "Housing benefit", "ESA", "DLA", "Overpayments"],
    relatedPracticeAreas: ["Community care", "Debt", "Housing"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Which benefit is involved (PIP, Universal Credit, ESA, housing benefit, or another), and is it a new claim, reconsideration, or tribunal appeal?",
    ],
    searchBoostTerms: [
      "benefits tribunal",
      "mandatory reconsideration",
      "PIP appeal",
      "universal credit",
      "welfare rights",
      "social security",
    ],
  },
  {
    slug: "personal_injury",
    canonicalName: "Personal Injury",
    matcherSlug: "personal_injury",
    aliases: ["injury claim", "accident claim"],
    userPhrases: ["injured in an accident", "RTA", "trip slip"],
    subIssues: ["Road traffic", "Employers liability", "Public liability", "Fatal claims"],
    relatedPracticeAreas: ["Clinical negligence"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Was this a road accident, an accident at work, a public place injury, or medical treatment gone wrong?",
    ],
    searchBoostTerms: [
      "personal injury",
      "compensation claim",
      "RTA",
      "road traffic accident",
      "employers liability",
      "CNF",
    ],
  },
  {
    slug: "clinical_negligence",
    canonicalName: "Clinical Negligence",
    matcherSlug: "personal_injury",
    aliases: ["medical negligence", "NHS negligence"],
    userPhrases: ["surgical error", "misdiagnosis claim", "hospital negligence"],
    subIssues: ["Surgery", "Birth injury", "Misdiagnosis", "Consent"],
    relatedPracticeAreas: ["Personal injury", "Inquests"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about NHS treatment, private healthcare, a birth injury, or a fatal incident?",
    ],
    searchBoostTerms: [
      "clinical negligence",
      "medical negligence",
      "NHS claim",
      "Bolt Burdon Kemp style",
      "CQC",
    ],
  },
  {
    slug: "wills_probate",
    canonicalName: "Wills and Probate",
    matcherSlug: "family",
    aliases: ["probate", "estate planning"],
    userPhrases: ["will writing", "probate after death", "executor", "LPA"],
    subIssues: ["Wills", "Probate", "Estates", "Trusts", "LPA", "Inheritance disputes"],
    relatedPracticeAreas: ["Tax", "Contentious probate"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about making a will, administering an estate after death, a trust, lasting powers of attorney, or a dispute over inheritance?",
    ],
    searchBoostTerms: [
      "wills and probate",
      "probate solicitor",
      "executor",
      "lasting power of attorney",
      "LPA",
      "estate administration",
    ],
  },
  {
    slug: "commercial",
    canonicalName: "Commercial Law",
    matcherSlug: "commercial",
    aliases: ["business law", "company law"],
    userPhrases: ["commercial contract", "shareholder dispute", "B2B"],
    subIssues: ["Contracts", "Shareholders", "Partnerships", "Debt recovery"],
    relatedPracticeAreas: ["Employment", "Insolvency"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about a contract dispute, a shareholder or partnership issue, unpaid invoices, or something else?",
    ],
    searchBoostTerms: [
      "commercial solicitor",
      "breach of contract",
      "shareholder dispute",
      "debt recovery",
      "B2B",
    ],
  },
  {
    slug: "consumer",
    canonicalName: "Consumer Law",
    matcherSlug: "commercial",
    aliases: ["consumer rights", "faulty goods"],
    userPhrases: ["refund", "trader dispute", "Section 75"],
    subIssues: ["Goods", "Services", "Travel", "Finance complaints"],
    relatedPracticeAreas: ["Debt", "Small claims"],
    emergencySignals: [],
    legalAidLikely: false,
    clarificationQuestions: [
      "Is this about faulty goods, poor services, a holiday or travel issue, or a finance/loan complaint?",
    ],
    searchBoostTerms: ["consumer law", "faulty goods", "trader", "small claims", "ombudsman"],
  },
  {
    slug: "debt",
    canonicalName: "Debt",
    matcherSlug: "commercial",
    aliases: ["debt advice", "bailiffs", "CCJ"],
    userPhrases: ["debt problem", "can't pay creditors", "bankruptcy"],
    subIssues: ["CCJ", "Bailiffs", "IVA", "Bankruptcy", "Council tax arrears"],
    relatedPracticeAreas: ["Housing", "Consumer"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about credit cards or loans, council tax, rent arrears, bailiffs, or insolvency options (IVA/bankruptcy)?",
    ],
    searchBoostTerms: ["debt advice", "CCJ", "bailiff", "StepChange", "IVA", "bankruptcy", "creditor"],
  },
  {
    slug: "education",
    canonicalName: "Education Law",
    matcherSlug: "family",
    aliases: ["school law", "SEN"],
    userPhrases: ["school exclusion", "EHCP", "SEN appeal"],
    subIssues: ["Exclusions", "EHCP", "Disability discrimination at school", "Higher education"],
    relatedPracticeAreas: ["Public law", "Discrimination"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a school exclusion, an EHCP or SEN support, disability discrimination, or a university issue?",
    ],
    searchBoostTerms: ["education law", "EHCP", "SEN", "school exclusion", "First-tier Tribunal SENDIST"],
  },
  {
    slug: "community_care",
    canonicalName: "Community Care",
    matcherSlug: "family",
    aliases: ["social care", "care needs"],
    userPhrases: ["care package", "NHS continuing healthcare", "local authority care"],
    subIssues: ["Care assessments", "CHC", "Care home disputes", "Direct payments"],
    relatedPracticeAreas: ["Mental health law", "Housing"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about a care needs assessment, NHS continuing healthcare, a care home placement, or funding disputes?",
    ],
    searchBoostTerms: ["community care", "care act", "CHC", "social services", "care package"],
  },
  {
    slug: "mental_health",
    canonicalName: "Mental Health Law",
    matcherSlug: "family",
    aliases: ["MHA", "sectioning"],
    userPhrases: ["Mental Health Act", "sectioned", "tribunal mental health"],
    subIssues: ["Hospital detention", "Community treatment orders", "Nearest relative"],
    relatedPracticeAreas: ["Community care", "Capacity"],
    emergencySignals: ["sectioned", "MHA urgent"],
    legalAidLikely: true,
    clarificationQuestions: [
      "Is this about detention under the Mental Health Act, a tribunal, a community treatment order, or capacity and best interests?",
    ],
    searchBoostTerms: ["mental health tribunal", "MHA", "section 2", "section 3", "nearest relative"],
  },
  {
    slug: "public_law",
    canonicalName: "Public Law and Judicial Review",
    matcherSlug: "family",
    aliases: ["judicial review", "JR"],
    userPhrases: ["judicial review", "challenge council decision", "public authority"],
    subIssues: ["JR", "Human rights", "Data/GDPR public sector", "Planning judicial review"],
    relatedPracticeAreas: ["Housing", "Immigration", "Community care"],
    emergencySignals: [],
    legalAidLikely: true,
    clarificationQuestions: [
      "Which public body or decision is involved (local authority, government department, regulator, or court/tribunal process)?",
    ],
    searchBoostTerms: ["judicial review", "public law", "JR", "unlawful decision", "Crown Court challenge"],
  },
];
