/**
 * Municipal capitals used for auto-generated client usernames on registration.
 * Israel is excluded entirely.
 */
const MUNICIPAL_CAPITALS = [
  "Abuja",
  "Accra",
  "Addis Ababa",
  "Algiers",
  "Amman",
  "Amsterdam",
  "Ankara",
  "Antananarivo",
  "Apia",
  "Ashgabat",
  "Asmara",
  "Astana",
  "Asunción",
  "Athens",
  "Baghdad",
  "Baku",
  "Bamako",
  "Bangkok",
  "Bangui",
  "Banjul",
  "Barcelona",
  "Basse-Terre",
  "Beijing",
  "Beirut",
  "Belgrade",
  "Belmopan",
  "Berlin",
  "Bern",
  "Bishkek",
  "Bissau",
  "Bogotá",
  "Brasília",
  "Bratislava",
  "Brazzaville",
  "Bridgetown",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Cairo",
  "Canberra",
  "Caracas",
  "Cardiff",
  "Castries",
  "Cayenne",
  "Charlotte Amalie",
  "Chișinău",
  "Colombo",
  "Conakry",
  "Copenhagen",
  "Dakar",
  "Damascus",
  "Dhaka",
  "Dili",
  "Djibouti",
  "Dodoma",
  "Doha",
  "Dublin",
  "Dushanbe",
  "Edinburgh",
  "Freetown",
  "Funafuti",
  "Gaborone",
  "Georgetown",
  "Guatemala City",
  "Hanoi",
  "Harare",
  "Havana",
  "Helsinki",
  "Honiara",
  "Islamabad",
  "Jakarta",
  "Juba",
  "Kabul",
  "Kampala",
  "Kathmandu",
  "Khartoum",
  "Kigali",
  "Kingston",
  "Kinshasa",
  "Kolkata",
  "Kuala Lumpur",
  "Kuwait City",
  "Kyiv",
  "Kyoto",
  "La Paz",
  "Lagos",
  "Libreville",
  "Lilongwe",
  "Lima",
  "Lisbon",
  "Ljubljana",
  "Lomé",
  "London",
  "Luanda",
  "Lusaka",
  "Luxembourg",
  "Madrid",
  "Majuro",
  "Malabo",
  "Malé",
  "Managua",
  "Manama",
  "Manila",
  "Maputo",
  "Maseru",
  "Mbabane",
  "Mexico City",
  "Minsk",
  "Mogadishu",
  "Monaco",
  "Monrovia",
  "Montevideo",
  "Moscow",
  "Muscat",
  "Nairobi",
  "Nassau",
  "N'Djamena",
  "New Delhi",
  "Nicosia",
  "Nouakchott",
  "Nouméa",
  "Nuku'alofa",
  "Oslo",
  "Ottawa",
  "Ouagadougou",
  "Palikir",
  "Panama City",
  "Paramaribo",
  "Paris",
  "Phnom Penh",
  "Podgorica",
  "Port Louis",
  "Port Moresby",
  "Port of Spain",
  "Porto",
  "Porto-Novo",
  "Prague",
  "Praia",
  "Pretoria",
  "Pyongyang",
  "Quito",
  "Rabat",
  "Rangoon",
  "Reykjavik",
  "Riga",
  "Riyadh",
  "Rome",
  "Roseau",
  "Sana'a",
  "San José",
  "San Juan",
  "San Salvador",
  "Santiago",
  "Santo Domingo",
  "São Paulo",
  "São Tomé",
  "Sarajevo",
  "Seoul",
  "Singapore",
  "Skopje",
  "Sofia",
  "Stockholm",
  "Suva",
  "Taipei",
  "Tallinn",
  "Tashkent",
  "Tbilisi",
  "Tegucigalpa",
  "Tehran",
  "Thimphu",
  "Tirana",
  "Tokyo",
  "Tripoli",
  "Tunis",
  "Ulaanbaatar",
  "Vaduz",
  "Valletta",
  "Vancouver",
  "Victoria",
  "Vienna",
  "Vientiane",
  "Vilnius",
  "Warsaw",
  "Wellington",
  "Windhoek",
  "Yamoussoukro",
  "Yaoundé",
  "Yaren",
  "Yerevan",
  "Zagreb",
] as const;

function slugifyCapital(capital: string): string {
  return capital
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/['’]/g, "")
    .replace(/\s+/g, "-");
}

/** Random username: municipal capital slug + 4-digit suffix (e.g. Lisbon-4821). */
export function generateMunicipalCapitalUsername(): string {
  const capital =
    MUNICIPAL_CAPITALS[crypto.randomInt(0, MUNICIPAL_CAPITALS.length)]!;
  const suffix = crypto.randomInt(1000, 10_000);
  return `${slugifyCapital(capital)}-${suffix}`;
}
